modules/admin/controllers/PostsController.php
<?php

namespace app\modules\admin\controllers;

use app\modules\main\models\Posts;
use app\modules\user\constants\Consts;
use app\modules\admin\models\PostsSearch;
use yii\web\Controller;
use Yii;
use yii\helpers\Url;
use yii\filters\VerbFilter;
use app\modules\main\components\helpers\NamesHelper;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;

class PostsController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /* Подробные коменты смотри в контроллере MyPosts в модуле юзера, очень похоже впадлу перепечатывать */

    public function actions()           // так то путь к сохранению фоток прописан в самом модуле, тут прописаны чтобы не вызывать ошибки
    {
        return [
            'image-upload' => [
                'class' => 'vova07\imperavi\actions\UploadFileAction',
                'url' => Url::to(['@web' . Yii::$app->params['posts.photos']]), // Directory URL address, where files are stored.
                'path' => Yii::getAlias('@webroot' . Yii::$app->params['posts.photos']), // Or absolute path to directory where files are stored.
                'translit' => true,
            ],
            'images-get' => [
                'class' => 'vova07\imperavi\actions\GetImagesAction',
                'url' => Url::to(['@web' . Yii::$app->params['posts.photos']]), // Directory URL address, where files are stored.
                'path' => Yii::getAlias('@webroot' . Yii::$app->params['posts.photos']), // Or absolute path to directory where files are stored.
                'options' => ['only' => ['*.jpg', '*.jpeg', '*.png', '*.gif', '*.ico']], // These options are by default.
            ],
            'files-get' => [
                'class' => 'vova07\imperavi\actions\GetFilesAction',
                'url' => Url::to(['@web' . Yii::$app->params['posts.files']]), // Directory URL address, where files are stored.
                'path' => Yii::getAlias('@webroot' . Yii::$app->params['posts.files']), // Or absolute path to directory where files are stored.
                'options' => ['only' => ['*.txt', '*.md', '*.pdf', '*.doc', '*.docx', '*.zip', '*.rar', '*.7z']], // These options are by default.
            ],
            'file-upload' => [
                'class' => 'vova07\imperavi\actions\UploadFileAction',
                'url' => Url::to(['@web' . Yii::$app->params['posts.files']]), // Directory URL address, where files are stored.
                'path' => Yii::getAlias('@webroot' . Yii::$app->params['posts.files']), // Or absolute path to directory where files are stored.
                'uploadOnlyImage' => false, // For any kind of files uploading.
                //'unique' => false,
                'translit' => true,
            ],
            'image-delete' => [
                'class' => 'vova07\imperavi\actions\DeleteFileAction',
                'url' => Url::to(['@web' . Yii::$app->params['posts.photos']]), // Directory URL address, where files are stored.
                'path' => Yii::getAlias('@webroot' . Yii::$app->params['posts.photos']), // Or absolute path to directory where files are stored.
            ],
            'file-delete' => [
                'class' => 'vova07\imperavi\actions\DeleteFileAction',
                'url' => Url::to(['@web' . Yii::$app->params['posts.files']]), // Directory URL address, where files are stored.
                'path' => Yii::getAlias('@webroot' . Yii::$app->params['posts.files']), // Or absolute path to directory where files are stored.
            ],
        ];
    }

    public function actionIndex()                               // отображаются все статьи, что есть в БД, кроме статуса "Архив"
    {
        $searchModel = new PostsSearch([
            'front' => false,
            'isArchive' => false,
            'locationFront' => false,
        ]);
        //debug($searchModel);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    public function actionArchive()
    {
        $searchModel = new PostsSearch([
            'front' => false,
            'isArchive' => true,
            'locationFront' => false,
        ]);
        //debug($searchModel);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('archive', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    public function actionProcess($id = false)
    {
        if ($id) {                                                           // понимаем, это новая новость, или редактирование
            $model = $this->findModel($id);
            $model->locationFront = false;
        } else {
            $model = new Posts(['locationFront' => true]);                   // задается место создания обьекта, в данном случае - фронтэнд, тобишь юзер
            $model->enterWorkflow();                                         // входим в воркфлоу, начальный статус
            $model->show_it = true;
            $model->saveIt();
            return $this->redirect(['process', 'id' => $model->id]);
        }

        if ($model->getWorkflowStatus()->getId() !== Consts::FLOW_ADMIN_PROCESS) {
            if ($model->checkAccess(Consts::FLOW_ADMIN_PROCESS)) {
                $model->sendToStatus(Consts::FLOW_ADMIN_PROCESS);
                $model->update();
            } else {
                throw new ForbiddenHttpException('Ошибка работы с воркфлоу!');
            }
        }

        if ($model->load(Yii::$app->request->post())) {
            if ($model->checkAccess(Consts::FLOW_ADMIN_CHECKING)) {
                $model->post_status = Consts::FLOW_ADMIN_CHECKING;
            } else {
                throw new ForbiddenHttpException('Ошибка работы с воркфлоу!');
            }
            if ($model->validate()) {
                if ($model->update()) {
                    Yii::$app->getSession()->setFlash('success', 'Данные сохранены!');
                    return $this->redirect(['view', 'id' => $model->id]);
                } else {
                    Yii::$app->getSession()->setFlash('danger', 'Данные не сохранены!');
                    return $this->redirect(['index']);
                }
            }
        }

        return $this->render('process', [
            'model' => $model,
        ]);
    }

    public function actionView($id)
    {
        $model = Posts::findOne($id);
        $model->locationFront = false;

        $status = $model->getWorkflowStatus()->getId();

        switch ($status) {
            case Consts::FLOW_ADMIN_PROCESS:
                if (!$model->checkAccess($status)) {
                    Yii::$app->getSession()->setFlash('danger', 'Заполните все поля, и сохранитесь, иначе предпросмотр не возможен!');
                    return $this->redirect(['process', 'id' => $id]);
                }
                break;

            case Consts::FLOW_ARCHIVE:
                break;

            case Consts::FLOW_USER_DENIED:
                break;

            default:
                if ($model->checkAccess(Consts::FLOW_ADMIN_CHECKING)) {
                    $model->sendToStatus(Consts::FLOW_ADMIN_CHECKING);
                    $model->update();
                }
                break;
        }

        if (empty($model->country_id) or empty($model->main_theme) or empty($model->sub_theme) or empty($model->body)) {
            Yii::$app->getSession()->setFlash('danger', 'Заполните все поля, иначе предпросмотр не возможен!');
            return $this->redirect(['process', 'id' => $id]);
        }

        $searchModel = new PostsSearch([
            'front' => true,
        ]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('view', [
            'model' => $model,
            'posts' => $dataProvider->getModels(),
        ]);
    }

    public function actionGetAction($id, $to_status)
    {
        $model = $this->findModel($id);

        $model->locationFront = false;

        if (!$model->checkAccess($to_status)) {
            throw new ForbiddenHttpException('Ошибка работы с воркфлоу!');
        }

        switch ($to_status) {
            case Consts::FLOW_ADMIN_PROCESS:
                return $this->redirect(['process', 'id' => $id]);
                break;

            case Consts::FLOW_ARCHIVE:
                $model->sendToStatus(Consts::FLOW_ARCHIVE);
                $model->update();
                return $this->redirect(['archive']);
                break;

            case Consts::FLOW_ADMIN_PUBLISHED:
                $model->{Consts::STATUS_ATTR} = Consts::FLOW_ADMIN_PUBLISHED;
                if ($model->validate()) {
                    $model->update();
                    return $this->redirect(['index']);
                }
                return $this->render('view', [
                    'model' => $model,
                ]);
                break;

            case Consts::FLOW_ADMIN_CHECKING:
                $model->sendToStatus(Consts::FLOW_ADMIN_CHECKING);
                $model->update();
                return $this->redirect(['view', 'id' => $id]);
                break;

            case Consts::FLOW_USER_DENIED:
                $model->{Consts::STATUS_ATTR} = Consts::FLOW_USER_DENIED;
                if ($model->validate()) {
                    $model->update();
                    return $this->redirect(['index']);
                }
                return $this->render('view', [
                    'model' => $model,
                ]);
                break;

            default:

modules/admin/views/posts/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use app\modules\admin\models\Countries;
use app\modules\user\constants\Consts;
use vova07\imperavi\Widget;
use yii\helpers\Url;
use kartik\datetime\DateTimePicker;

?>

<div class="margin">
    <?php
    //Pjax::begin();
    $form = ActiveForm::begin([
        'id' => 'new-post-form',
        'options' => [
            //'class' => 'form-horizontal',
            'data-pjax' => true,
        ],
    ]);
    $countries = ArrayHelper::map(Countries::find()->all(), 'id', 'name');
    $params = [
        'prompt' => 'Выберите страну...',
        'class' => 'form-control',
    ];
    echo $form->errorSummary($model);
    ?>

    <?= $form->field($model, 'country_id', ['inputOptions' => ['autocomplete' => 'off']])->dropDownList($countries, $params)->label('Выберите страну') ?>

    <?php
    if (!empty($model->upload_at)) {
        $model->upload_at = date('d.m.Y H:i:s', $model->upload_at);
    }
    echo '<label class="control-label">Время публикации</label>';
    echo DateTimePicker::widget([
        'type' => DateTimePicker::TYPE_BUTTON,
        'layout' => '{picker} {remove} {input}',
        'options' => [
            'type' => 'text',
            'readonly' => true,
            'class' => 'text-muted small',
            'style' => 'border:none;background:none',
        ],
        'model' => $model,
        'attribute' => 'upload_at',
        'name' => 'upload_at',
        'value' => null,
        'readonly' => true,
        'pluginOptions' => [
            'autoclose' => true,
            'format' => 'dd.mm.yyyy hh:ii',
            'todayHighlight' => true,
            'startDate' => 'd',
        ]
    ]);
    echo Html::error($model, 'upload_at', ['class' => 'daterror']);
    ?>

    <?= $form->field($model, 'main_theme', ['inputOptions' => ['autocomplete' => 'off']])->textInput(['maxlength' => true, 'class' => 'form-control']) ?>

    <?= $form->field($model, 'sub_theme', ['inputOptions' => ['autocomplete' => 'off']])->textarea(['rows' => 3, 'class' => 'form-control']) ?>



    <?php
    echo $form->field($model, 'body')->widget(Widget::className(), [
        'settings' => [
            'lang' => 'ru',
            'minHeight' => 200,
            'imageUpload' => Url::to(['posts/image-upload', 'id' => $model->id]),
            'imageManagerJson' => Url::to(['posts/images-get', 'id' => $model->id]),
            'fileUpload' => Url::to(['posts/file-upload', 'id' => $model->id]),
            'fileManagerJson' => Url::to(['posts/files-get', 'id' => $model->id]),
            'imageDelete' => Url::to(['posts/image-delete', 'id' => $model->id]),
            'fileDelete' => Url::to(['posts/file-delete', 'id' => $model->id]),
            'plugins' => [
                'fullscreen',
            ],
        ],
        'plugins' => [
            'filemanager' => 'vova07\imperavi\bundles\FileManagerAsset',
            'imagemanager' => 'vova07\imperavi\bundles\ImageManagerAsset',

        ],
    ]);
    //echo Html::error($model, 'body', ['class' => 'daterror']);
    echo $form->field($model, 'show_it', ['inputOptions' => ['autocomplete' => 'off']])->checkbox();
    ?>

    <div class="form-group">
        <?php
        $nextSteps = $model->nextSteps();
        //debug($model->fromArchive);
        foreach ($nextSteps as $step) {
            if ($step['name'] == Consts::FLOW_ARCHIVE) {
                $step['meta']['actionLabel'] = 'Сохранить и положить в архив';
            }
            echo Html::submitButton(Html::encode($step['meta']['actionLabel']), ['class' => 'btn btn-success']);
        }
        ?>
    </div>

    <?php
    ActiveForm::end();
    ?>
</div>

modules/admin/views/posts/archive.php
<?php

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use app\modules\admin\models\Countries;
use kartik\date\DatePicker;
use app\modules\main\components\widgets\Alert;

$this->title = 'Архив';
$this->params['breadcrumbs'][] = ['label' => Html::encode(Yii::t('app', 'NAV_ADMIN')), 'url' => ['/admin/default/index']];
$this->params['breadcrumbs'][] = ['label' => 'Статьи', 'url' => ['posts/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<main role="main">
    <!-- Content -->
    <article>
        <header class="section background-primary text-center">
            <h1 class="text-white margin-bottom-0 text-size-50 text-thin text-line-height-1"><?= Html::encode($this->title) ?></h1>
        </header>
        <div class="section background-white">
            <div class="line">
                <div class="margin">
                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'filterModel' => $searchModel,
                        'columns' => [
                            ['class' => 'yii\grid\SerialColumn'],

                            [
                                'attribute' => 'country_id',
                                'value' => 'country.name',
                                'filter' => ArrayHelper::map(Countries::find()->all(), 'id', 'name'),
                                'options' => ['width' => '150'],
                            ],

                            [
                                'filter' => DatePicker::widget([
                                    'model' => $searchModel,
                                    'attribute' => 'date_from_create',
                                    'attribute2' => 'date_to_create',
                                    'type' => DatePicker::TYPE_RANGE,
                                    'separator' => '<i class="glyphicon glyphicon-resize-horizontal"></i>',
                                    'pluginOptions' => [
                                        'format' => 'dd.mm.yyyy',
                                        'autoclose' => false,
                                    ],
                                    'options' => [
                                        // you can hide the input by setting the following
                                        'autocomplete' => 'off',
                                    ]
                                ]),
                                'attribute' => 'created_at',
                                'contentOptions' => ['style' => 'width: 25%;'],
                                'format' => ['date', 'php:d.m.Y H:i:s'],
                            ],

                            //'author_id',
                            //'show_it',
                            [
                                'attribute' => 'show_it',
                                'format' => 'raw',
                                'value' => function ($data) {
                                    return $data->show_it ? '<span class="label label-success">Вкл</span>' : '<span class="label label-danger">Выкл</span>';
                                },
                                'filter' => array(
                                    0 => 'Выкл',
                                    1 => 'Вкл',
                                ),
                                //'options' => ['width' => '150'],
                            ],
                            //'main_theme',
                            [
                                'attribute' => 'main_theme',
                                'format' => 'raw',
                                'value' => function ($model) {
                                    return Html::a(Html::encode($model->main_theme), ['view', 'id' => $model->id]);
                                }
                            ],
                            //'sub_theme',
                            //'body:ntext',

                            [
                                'class' => 'yii\grid\ActionColumn',
                                'contentOptions' => ['style' => 'white-space: nowrap; text-align: center; letter-spacing: 0.1em; max-width: 7em;'],
                                'template' => '{view}',
                            ],
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </article>
</main>

modules/admin/views/posts/index.php
<?php

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use app\modules\admin\models\Countries;
use kartik\date\DatePicker;
use app\modules\main\components\widgets\Alert;
use app\modules\user\constants\Consts;

$this->title = Html::encode('Статьи');
$this->params['breadcrumbs'][] = ['label' => Html::encode(Yii::t('app', 'NAV_ADMIN')), 'url' => ['/admin/default/index']];
$this->params['breadcrumbs'][] = Html::encode($this->title);
?>
<div class="posts-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Html::encode('Создать статью'), ['process'], ['class' => 'btn btn-success margin-right-40']) ?>
        <?= Html::a(Html::encode('Архив'), ['archive'], ['class' => 'btn btn-default']) ?>
        <?= Html::a(Html::encode('Управление странами'), ['/admin/countries/index'], ['class' => 'btn btn-primary']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute' => 'country_id',
                'value' => 'country.name',
                'filter' => ArrayHelper::map(Countries::find()->all(), 'id', 'name'),
                'options' => ['width' => '150'],
            ],

            [
                'filter' => DatePicker::widget([
                    'model' => $searchModel,
                    'attribute' => 'date_from_upload',
                    'attribute2' => 'date_to_upload',
                    'type' => DatePicker::TYPE_RANGE,
                    'separator' => '<i class="glyphicon glyphicon-resize-horizontal"></i>',
                    'pluginOptions' => [
                        'format' => 'dd.mm.yyyy',
                        'autoclose' => false,
                    ],
                    'options' => [
                        // you can hide the input by setting the following
                        'autocomplete' => 'off',
                    ]
                ]),
                'attribute' => 'upload_at',
                'contentOptions' => ['style' => 'width: 20%;'],
                'format' => ['date', 'php:d.m.Y H:i:s'],
            ],

            [
                'filter' => DatePicker::widget([
                    'model' => $searchModel,
                    'attribute' => 'date_from_create',
                    'attribute2' => 'date_to_create',
                    'type' => DatePicker::TYPE_RANGE,
                    'separator' => '<i class="glyphicon glyphicon-resize-horizontal"></i>',
                    'pluginOptions' => [
                        'format' => 'dd.mm.yyyy',
                        'autoclose' => false,
                    ],
                    'options' => [
                        // you can hide the input by setting the following
                        'autocomplete' => 'off',
                    ]
                ]),
                'attribute' => 'updated_at',
                'contentOptions' => ['style' => 'width: 20%;'],
                'format' => ['date', 'php:d.m.Y H:i:s'],
            ],

            [
                'attribute' => 'show_it',
                'format' => 'raw',
                'value' => function ($data) {
                    return $data->show_it ? '<span class="label label-success">ДА</span>' : '<span class="label label-danger">НЕТ</span>';
                }
            ],

            [
                'attribute' => Consts::STATUS_ATTR,
                'format' => 'raw',
                'value' => function ($data) {
                    return '<span class="label ' . $data->getWorkflowStatus()->getMetadata('labelClass') . '">' . $data->getWorkflowStatus()->getLabel() . '</span>';
                },
                'filter' => ArrayHelper::map(
                    $searchModel->allSteps(
                        $unset = array(
                            Consts::FLOW_NEW,
                            Consts::FLOW_ARCHIVE
                        )
                    ),
                    'name',
                    'label'
                ),
            ],

            [
                'attribute' => 'main_theme',
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::a(Html::encode($model->main_theme), ['view', 'id' => $model->id]);
                }
            ],

            [
                'class' => 'yii\grid\ActionColumn',
                'contentOptions' => ['style' => 'white-space: nowrap; text-align: center; letter-spacing: 0.1em; max-width: 7em;'],
                'template' => '{view} {delete}',
            ],
        ],
    ]); ?>


</div>

modules/admin/views/posts/process.php
<?php

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use yii\widgets\Pjax;
use app\modules\main\components\widgets\Alert;

$this->title = 'Работа со статьёй';
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'TITLE_PROFILE'), 'url' => ['profile/index']];
$this->params['breadcrumbs'][] = ['label' => 'Мои статьи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<main role="main">
    <!-- Content -->
    <article>
        <header class="section background-primary text-center">
            <h1 class="text-white margin-bottom-0 text-size-50 text-thin text-line-height-1">
                <?php
                echo Html::encode($this->title)
                ?>
            </h1>
        </header>
        <div class="section background-white">
            <div class="line">
                <?php Pjax::begin(['id' => 'new_note']) ?>
                <?= $this->render('_form', [
                    'model' => $model,
                ]) ?>
                <?php Pjax::end(); ?>

            </div>
        </div>
    </article>
</main>