modules/user/controllers/MyPostsController.php
<?php

namespace app\modules\user\controllers;

use app\modules\main\models\Posts;
use app\modules\user\constants\Consts;
use app\modules\user\models\MyPostsSearch;
use yii\web\Controller;
use Yii;
use yii\helpers\Url;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\modules\main\components\helpers\NamesHelper;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;

class MyPostsController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],

            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['user'],
                    ],
                ],
            ],
        ];
    }

    public function actions()               // пути к расположению файлов прописал в самом модуле расширения, тут чисто чтобы не валилось в ошибку
    {
        return [
            'image-upload' => [
                'class' => 'vova07\imperavi\actions\UploadFileAction',
                'url' => Url::to(['@web' . Yii::$app->params['posts.photos']]), // Directory URL address, where files are stored.
                'path' => Yii::getAlias('@webroot' . Yii::$app->params['posts.photos']), // Or absolute path to directory where files are stored.
                'translit' => true,
            ],
            'images-get' => [
                'class' => 'vova07\imperavi\actions\GetImagesAction',
                'url' => Url::to(['@web' . Yii::$app->params['posts.photos']]), // Directory URL address, where files are stored.
                'path' => Yii::getAlias('@webroot' . Yii::$app->params['posts.photos']), // Or absolute path to directory where files are stored.
                'options' => ['only' => ['*.jpg', '*.jpeg', '*.png', '*.gif', '*.ico']], // These options are by default.
            ],
            'files-get' => [
                'class' => 'vova07\imperavi\actions\GetFilesAction',
                'url' => Url::to(['@web' . Yii::$app->params['posts.files']]), // Directory URL address, where files are stored.
                'path' => Yii::getAlias('@webroot' . Yii::$app->params['posts.files']), // Or absolute path to directory where files are stored.
                'options' => ['only' => ['*.txt', '*.md', '*.pdf', '*.doc', '*.docx', '*.zip', '*.rar', '*.7z']], // These options are by default.
            ],
            'file-upload' => [
                'class' => 'vova07\imperavi\actions\UploadFileAction',
                'url' => Url::to(['@web' . Yii::$app->params['posts.files']]), // Directory URL address, where files are stored.
                'path' => Yii::getAlias('@webroot' . Yii::$app->params['posts.files']), // Or absolute path to directory where files are stored.
                'uploadOnlyImage' => false, // For any kind of files uploading.
                //'unique' => false,
                'translit' => true,
            ],
            'image-delete' => [
                'class' => 'vova07\imperavi\actions\DeleteFileAction',
                'url' => Url::to(['@web' . Yii::$app->params['posts.photos']]), // Directory URL address, where files are stored.
                'path' => Yii::getAlias('@webroot' . Yii::$app->params['posts.photos']), // Or absolute path to directory where files are stored.
            ],
            'file-delete' => [
                'class' => 'vova07\imperavi\actions\DeleteFileAction',
                'url' => Url::to(['@web' . Yii::$app->params['posts.files']]), // Directory URL address, where files are stored.
                'path' => Yii::getAlias('@webroot' . Yii::$app->params['posts.files']), // Or absolute path to directory where files are stored.
            ],
        ];
    }

    public function actionIndex()                           // отоброжения всех статей автора (юзера)
    {
        $searchModel = new MyPostsSearch([
            'isArchive' => false,                           // чтобы исключить записи в архиве
            'locationFront' => true,                        // для корректной работы повдение, проверки следующих статусов и тд
        ]);
        //debug($searchModel);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    public function actionArchive()                     // отображение записей, лежащих в архиве
    {
        $searchModel = new MyPostsSearch([
            'isArchive' => true,                        // чтобы исключить все статьи, кроме тех, что со статусом "архив"
            'locationFront' => true,                    // для работы поведение, указываем, что это сторона юзеров
        ]);
        //debug($searchModel);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('archive', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    public function actionProcess($id = false)
    {
        if ($id) {                                                           // понимаем, это новая новость, или редактирование
            $model = $this->findModel($id);
            $model->locationFront = true;

            if (!\Yii::$app->user->can('updateOwnPosts', ['post' => $model])) {
                throw new ForbiddenHttpException('Доступ закрыт! Вы не являетесь автором статьи!');
            }
        } else {
            $model = new Posts(['locationFront' => true]);                   // задается место создания обьекта, в данном случае - фронтэнд, тобишь юзер
            $model->enterWorkflow();                                         // входим в воркфлоу, начальный статус
            $model->show_it = true;                                          // флаг "удаленности" статьи, тоесть она не удалена
            $model->saveIt();                                                // создание обьекта этой статьи в БД
            return $this->redirect(['process', 'id' => $model->id]);         // переадресация на этот же экшн, чтобы исключить создание кучи лишних обьектов статей при обновлениях страницы, и просто так
        }

        if ($model->getWorkflowStatus()->getId() !== Consts::FLOW_USER_PROCESS) {       // если по какой-то причине у статьи статус не "корректирование"
            if ($model->checkAccess(Consts::FLOW_USER_PROCESS)) {                       // проверяем, возможен ли переход с текущего статуса на корректирование
                $model->sendToStatus(Consts::FLOW_USER_PROCESS);                        // переводи на этот статус
                $model->update();                                                       // обновляем данные в БД
            } else {
                throw new ForbiddenHttpException('Ошибка работы с воркфлоу!');
            }
        }

        if ($model->load(Yii::$app->request->post())) {                                  // загружаем данные из формы
            if ($model->checkAccess(Consts::FLOW_USER_PREVIEW)) {                        // проверяем, возможен ли переход на статус "Предпросмотр"
                $model->post_status = Consts::FLOW_USER_PREVIEW;                         // присваиваю статус обьтекту статьи таким образом, чтобы сработала валидация (валидация при переходе на определенный статус)
            } else {
                throw new ForbiddenHttpException('Ошибка работы с воркфлоу!');
            }
            if ($model->validate()) {                                                    // валидация
                if ($model->update()) {                                                  // обновление обьекта в БД
                    Yii::$app->getSession()->setFlash('success', 'Данные сохранены!');
                    return $this->redirect(['view', 'id' => $model->id]);
                } else {
                    Yii::$app->getSession()->setFlash('danger', 'Данные не сохранены!');
                    return $this->redirect(['index']);
                }
            }
        }

        return $this->render('process', [
            'model' => $model,
        ]);
    }

    public function actionView($id)
    {
        $model = $this->findModel($id);                                                 // находим обьект статьи в БД
        $model->locationFront = true;                                                   // задаем положение обьекта (у юзеров)

        if ($model->getWorkflowStatus()->getId() == Consts::FLOW_USER_PROCESS) {        // если у обьекта статус "корректировка" переводим страницу на экшн процесса и заставляем юзера жмакнуть кнопочку сохранить
            Yii::$app->getSession()->setFlash('danger', 'Заполните все поля, и сохранитесь, иначе предпросмотр не возможен!');
            return $this->redirect(['process', 'id' => $id]);
        }

        if (empty($model->country_id) or empty($model->main_theme) or empty($model->sub_theme) or empty($model->body)) {        // проверяем, заполнены ли ключевые поля, чтобы вьюшка не ломалась
            Yii::$app->getSession()->setFlash('danger', 'Заполните все поля, иначе предпросмотр не возможен!');
            return $this->redirect(['process', 'id' => $id]);                                                                   // если нет, заставляем заполнить
        }

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionGetAction($id, $to_status)                                                    // экшн распределения по статусам
    {
        $model = $this->findModel($id);                                                                 // находим нужную модель

modules/user/controllers/ProfileController.php
<?php

namespace app\modules\user\controllers;

use app\modules\user\models\User;
use yii\filters\AccessControl;
use yii\web\Controller;
use Yii;
use app\modules\user\forms\ProfileUpdateForm;
use app\modules\user\forms\PasswordChangeForm;
use app\modules\admin\models\FilesUpload;
use yii\web\UploadedFile;

class ProfileController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['user'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index', [
            'model' => $this->findModel(),
        ]);
    }

    public function actionUpdateEmail()
    {
        $user = $this->findModel();
        $model = new ProfileUpdateForm($user);

        if ($model->load(Yii::$app->request->post()) && $model->update()) {
            Yii::$app->getSession()->setFlash('success', 'Новый Email сохранен!');
            return $this->redirect(['index']);
        } else {
            return $this->render('update-email', [
                'model' => $model,
            ]);
        }
    }

    public function actionPasswordChange()
    {
        $user = $this->findModel();
        $model = new PasswordChangeForm($user);

        if ($model->load(Yii::$app->request->post()) && $model->changePassword()) {
            Yii::$app->getSession()->setFlash('success', 'Новый пароль сохранен успешно!');
            return $this->redirect(['index']);
        } else {
            return $this->render('passwordChange', [
                'model' => $model,
            ]);
        }
    }

    public function actionPicChange()
    {
        $user = $this->findModel();
        $files_upload = new FilesUpload([
            'scenario' => FilesUpload::SCENARIO_UPDATE,
        ]);
        $file_type = 'images';                                                                                  // определяем тип заружаемых данных
        $path = '/var/www/start2/docs/'.Yii::$app->params['users.profile.photos'];
        $file_names = false;
        $preview = $files_upload->initialPreviewGenerator($user, Yii::$app->params['users.profile.photos'], 'user_pic');

        if (Yii::$app->request->isPost) {
            $files_upload->images = UploadedFile::getInstances($files_upload, 'images');
            if (!empty($files_upload->images)) {                                                                //если файлы загружены - сохраняем их, запись в бд идет в модели
                if ($user->user_pic != null and file_exists($path.$user->user_pic)) {
                    unlink($path.$user->user_pic);                                                                     // на всякий подчищаем всю папку, нужна только одна текущая фотка
                }
                $file_names = $files_upload->uploadThis($file_type, $path);                                     //сохраняем
                if (!$file_names) {
                    Yii::$app->getSession()->setFlash('danger', 'Данные не сохранены из-за фотографии!');
                    return $this->redirect(['index']);
                }
            }
            if ($file_names) {
                foreach ($file_names as $name) {
                    $user->user_pic = $name;
                }
            }
            if ($user->save()) {
                Yii::$app->getSession()->setFlash('success', 'Данные сохранены!');
                return $this->redirect(['index']);
            } else {
                Yii::$app->getSession()->setFlash('danger', 'Данные не сохранены!');
                return $this->redirect(['index']);
            }
        }

        return $this->render('pic-change', [
            //'model' => $model,
            'files_upload' => $files_upload,
            'preview' => $preview,
        ]);
    }

    public function actionDeleteFiles($img_id, $img_name)                         //экшн для удаления фоток из картик инпута
    {
        $path = __DIR__.'/../../../'.Yii::$app->params['users.profile.photos'];
        $user = $this->findModel();                                    //подчищаем названия файлов в базе, в обоих строках
        if (file_exists($path.$user->user_pic)) {
            unlink($path.$user->user_pic);
            $user->user_pic = null;
            $user->save();
        }
        return '{}';                                                               //надо вернуть это, чтобы картик инпут не вываливался в ошибку
    }

    /**
     * @return User the loaded model
     */
    private function findModel()
    {
        return User::findOne(Yii::$app->user->identity->getId());
    }
}

modules/user/views/my-posts/archive.php
<?php

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use app\modules\admin\models\Countries;
use kartik\date\DatePicker;
use app\modules\main\components\widgets\Alert;

$this->title = 'Архив';
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'TITLE_PROFILE'), 'url' => ['profile/index']];
$this->params['breadcrumbs'][] = ['label' => 'Мои статьи', 'url' => ['my-posts/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<main role="main">
    <!-- Content -->
    <article>
        <header class="section background-primary text-center">
            <h1 class="text-white margin-bottom-0 text-size-50 text-thin text-line-height-1"><?= Html::encode($this->title) ?></h1>
        </header>
        <div class="section background-white">
            <div class="line">
                <div class="margin">
                    <?= Alert::widget([
                        'options' => [
                            'class' => 'footer-alert text-thin text-white',
                        ],
                    ]) ?>
                </div>
            </div>
            <div class="line">
                <div class="margin margin-bottom-40">
                    <?= Breadcrumbs::widget([
                        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                    ]) ?>
                </div>
            </div>
            <div class="line">
                <div class="margin">
                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'filterModel' => $searchModel,
                        'columns' => [
                            ['class' => 'yii\grid\SerialColumn'],

                            [
                                'attribute' => 'country_id',
                                'value' => 'country.name',
                                'filter' => ArrayHelper::map(Countries::find()->all(), 'id', 'name'),
                                'options' => ['width' => '150'],
                            ],

                            [
                                'filter' => DatePicker::widget([
                                    'model' => $searchModel,
                                    'attribute' => 'date_from_create',
                                    'attribute2' => 'date_to_create',
                                    'type' => DatePicker::TYPE_RANGE,
                                    'separator' => '<i class="glyphicon glyphicon-resize-horizontal"></i>',
                                    'pluginOptions' => [
                                        'format' => 'dd.mm.yyyy',
                                        'autoclose' => false,
                                    ],
                                    'options' => [
                                        // you can hide the input by setting the following
                                        'autocomplete' => 'off',
                                    ]
                                ]),
                                'attribute' => 'created_at',
                                'contentOptions' => ['style' => 'width: 25%;'],
                                'format' => ['date', 'php:d.m.Y H:i:s'],
                            ],

                            //'author_id',
                            //'show_it',
                            [
                                'attribute' => 'show_it',
                                'format' => 'raw',
                                'value' => function ($data) {
                                    return $data->show_it ? '<span class="label label-success">Вкл</span>' : '<span class="label label-danger">Выкл</span>';
                                },
                                'filter' => array(
                                    0 => 'Выкл',
                                    1 => 'Вкл',
                                ),
                                //'options' => ['width' => '150'],
                            ],
                            //'main_theme',
                            [
                                'attribute' => 'main_theme',
                                'format' => 'raw',
                                'value' => function ($model) {
                                    return Html::a(Html::encode($model->main_theme), ['view', 'id' => $model->id]);
                                }
                            ],
                            //'sub_theme',
                            //'body:ntext',

                            [
                                'class' => 'yii\grid\ActionColumn',
                                'contentOptions' => ['style' => 'white-space: nowrap; text-align: center; letter-spacing: 0.1em; max-width: 7em;'],
                                'template' => '{view}',
                            ],
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </article>
</main>

modules/user/views/my-posts/index.php
<?php

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use app\modules\admin\models\Countries;
use kartik\date\DatePicker;
use app\modules\main\components\widgets\Alert;
use app\modules\user\constants\Consts;

$this->title = 'Мои статьи';
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'TITLE_PROFILE'), 'url' => ['profile/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<main role="main">
    <!-- Content -->
    <article>
        <header class="section background-primary text-center">
            <h1 class="text-white margin-bottom-0 text-size-50 text-thin text-line-height-1"><?= Html::encode($this->title) ?></h1>
        </header>
        <div class="section background-white">
            <div class="line">
                <div class="margin">
                    <?= Alert::widget([
                        'options' => [
                            'class' => 'footer-alert text-thin text-white',
                        ],
                    ]) ?>
                </div>
            </div>
            <div class="line">
                <div class="margin margin-bottom-40">
                    <?= Breadcrumbs::widget([
                        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                    ]) ?>
                </div>
            </div>
            <div class="line" style="padding-left: 0;">
                <div class="margin-bottom">
                    <?php
                    echo Html::a(Html::encode('Создать статью'), ['process'], ['class' => 'button background-primary border-radius text-white margin-right-40']);
                    echo Html::a(Html::encode('Архив'), ['archive'], ['class' => 'button button-primary-stroke border-radius']);
                    //debug($searchModel->allSteps());
                    ?>
                </div>
            </div>
            <div class="line">
                <div class="margin">
                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'filterModel' => $searchModel,
                        'columns' => [
                            ['class' => 'yii\grid\SerialColumn'],

                            [
                                'attribute' => 'country_id',
                                'value' => 'country.name',
                                'filter' => ArrayHelper::map(Countries::find()->all(), 'id', 'name'),
                                'options' => ['width' => '150'],
                            ],

                            [
                                'filter' => DatePicker::widget([
                                    'model' => $searchModel,
                                    'attribute' => 'date_from_create',
                                    'attribute2' => 'date_to_create',
                                    'type' => DatePicker::TYPE_RANGE,
                                    'separator' => '<i class="glyphicon glyphicon-resize-horizontal"></i>',
                                    'pluginOptions' => [
                                        'format' => 'dd.mm.yyyy',
                                        'autoclose' => false,
                                    ],
                                    'options' => [
                                        // you can hide the input by setting the following
                                        'autocomplete' => 'off',
                                    ]
                                ]),
                                'attribute' => 'created_at',
                                'contentOptions' => ['style' => 'width: 25%;'],
                                'format' => ['date', 'php:d.m.Y H:i:s'],
                            ],

                            [
                                'attribute' => Consts::STATUS_ATTR,
                                'format' => 'raw',
                                'value' => function ($data) {
                                    return '<span class="label '.$data->getWorkflowStatus()->getMetadata('labelClass').'">'.$data->getWorkflowStatus()->getLabel().'</span>';
                                },
                                'filter' => ArrayHelper::map(
                                    $searchModel->allSteps(
                                        $unset = array(
                                            Consts::FLOW_NEW,
                                            Consts::FLOW_ARCHIVE
                                        )
                                    ),
                                    'name',
                                    'label'
                                ),
                            ],

                            [
                                'attribute' => 'main_theme',
                                'format' => 'raw',
                                'value' => function ($model) {
                                    return Html::a(Html::encode($model->main_theme), ['view', 'id' => $model->id]);
                                }
                            ],

                            [
                                'class' => 'yii\grid\ActionColumn',
                                'contentOptions' => ['style' => 'white-space: nowrap; text-align: center; letter-spacing: 0.1em; max-width: 7em;'],
                                'template' => '{view} {delete}',
                            ],
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </article>
</main>

modules/user/views/my-posts/process.php
<?php

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use yii\widgets\Pjax;
use app\modules\main\components\widgets\Alert;

$this->title = 'Работа со статьёй';
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'TITLE_PROFILE'), 'url' => ['profile/index']];
$this->params['breadcrumbs'][] = ['label' => 'Мои статьи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<main role="main">
    <!-- Content -->
    <article>
        <header class="section background-primary text-center">
            <h1 class="text-white margin-bottom-0 text-size-50 text-thin text-line-height-1">
                <?php
                echo Html::encode($this->title)
                ?>
            </h1>
        </header>
        <div class="section background-white">
            <div class="line">
                <div class="margin">
                    <?= Alert::widget([
                        'options' => [
                            'class' => 'footer-alert text-thin text-white',
                        ],
                    ]) ?>
                </div>
            </div>
            <div class="line">
                <div class="margin margin-bottom-40">
                    <?= Breadcrumbs::widget([
                        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                    ]) ?>
                </div>
            </div>
            <div class="line">
                <?php Pjax::begin(['id' => 'new_note']) ?>
                <?= $this->render('_form', [
                    'model' => $model,
                ]) ?>
                <?php Pjax::end(); ?>

            </div>
        </div>
    </article>
</main>

modules/user/views/my-posts/view.php
<?php

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use app\modules\main\components\widgets\Alert;
use app\modules\user\constants\Consts;

$this->title =  Html::encode('Создать статью');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'TITLE_PROFILE'), 'url' => ['profile/index']];
$this->params['breadcrumbs'][] = ['label' => 'Мои статьи', 'url' => ['my-posts/index']];
$this->params['breadcrumbs'][] = $this->title;

?>

<!-- MAIN -->
<main role="main">
    <!-- Content -->
    <article>
        <header class="section background-primary text-center">
            <h1 class="text-white margin-bottom-0 text-size-50 text-thin text-line-height-1"><?= Html::encode($model->country->name) ?></h1>
        </header>

        <div class="section background-white">
            <div class="line">
                <div class="margin">
                    <?= Alert::widget([
                        'options' => [
                            'class' => 'footer-alert text-thin text-white',
                        ],
                    ]) ?>
                </div>
            </div>
            <div class="line">
                <?= Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ]) ?>
            </div>
            <div class="line">
                <?php
                $nextSteps = $model->nextSteps();
                //debug($nextSteps);
                echo '<div class="margin-bottom">';
                foreach ($nextSteps as $step) {
                    /* if ($step['name'] == Consts::FLOW_USER_PREVIEW) {
                        $step['meta']['actionLabel'] = 'Извлечь из архива';
                    } */
                    echo Html::a(Html::encode($step['meta']['actionLabel']), ['get-action', 'id' => $model->id, 'to_status' => $step['name']], ['class' => 'button button-primary-stroke margin-right']);
                }
                echo Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
                    'class' => 'button cancel-btn',
                    'data' => [
                        'confirm' => 'Вы уверены, что хотите удалить эту статью?',
                        'method' => 'post',
                    ],
                ]);
                echo '</div>';
                ?>
            </div>
            <div class="line">
                <h2 class="text-size-30"><?= $model->main_theme ?></h2>
                <?= $model->body ?>
            </div>
        </div>
    </article>
</main>